version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: chatify-app
        container_name: chatify-app
        ports:
            - "8002:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
            - APP_URL=http://localhost:8002
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: chatify-db
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql

    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        ports:
            - "1025:1025"
            - "8025:8025"

volumes:
    db_data:
